version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: my-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://yaswanthchennareddy25:vhG7yWS1xL0swoE0@cluster0.r78ls.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000  # Set the port for your application
    depends_on:
      - mongo

volumes:
  mongo_data:
